### ISSUE TITLE
Operators in calculations are case sensitive

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/javarosa#512]
#### Software versions 
JavaRosa v2.17.0 and older versions

#### Problem description
In calculations you can use operators like: and, or, div, mod but you can't use AND, OR etc.
it breaks form parsing. I think it's not intuitive and have seen some questions on the forum where it was a problem why a user was't able to use a form.

**Comment by lognaturel** [comment]
Can you please link to the forum posts where this came up?

This is a spec-level conversation. Operators come from XML which is case-sensitive. If this gets changed, it should be part of the official spec. That said, it might not be a reasonable change to make because for tools that use off-the-shelf XPath evaluators there's probably no way to change operator case sensitivity.

**Comment by grzesiek2010** [comment]
It's difficult to find it now but I'm sure I answered such questions...
There is a similar problem with regex for example. Some calcs might capitalize the first letter automatically (I had such a situation), then it starts with Regex not regex (if you don't correct it manually), it doesn't throw any exception when you convert your form but then doesn't work in Collect.
That's why I thought it would be better for our users to avoid such problems.

**Comment by lognaturel** [comment]
As noted above, this first needs to be considered as a spec-level proposal. Since the case-sensitivity comes from XPath, I feel strongly that we should not change it at the XForms spec level. We possibly could do a transformation from `pyxform` but I'd like to see evidence that this is a common problem first (because we're sitting on other common problems we need to fix!).
